version: '3.4'

services:
  vault-agent:
    image: vault
    restart: always
    command: [ 'vault', 'agent', '-config=/vault/API/vault-agent/config-vault-agent-template-debug.hcl']
    volumes:
      - ./:/vault/API:rw
    cap_add:
      - IPC_LOCK

networks:
  default:
    name: starlight_network
    external: true